### ISSUE TITLE
Diakritika při insertu do databáze

### ISSUE THREAD

**Issue by Skoreto** [Skoreto/FitSpirit#1]
Některé diakritické znaky jsou při vkládání názvů do databáze nahrazeny otazníky.

**Comment by TeeJay-net** [comment]
https://github.com/Skoreto/FitSpirit/commit/4f65d8104b184608b1fe04c12944521f64afa2f3#commitcomment-15538797 latin2_czech_cs problém vyřešilo? 

Normálně se tohle řeší jen jedním SQL řádkem navíc, který se o překlad postará před každou komunikací... musel bych chvíli hledat.
A v 99.9% případů se používá utf8_foo. UTF8 je jasný a to, co je za podtržítkem, určuje, jak budou fungovat funkce na abecední řazení, protože např. znaky s diakritikou v anglický abecedě nejsou, takže třeba s utf8_general_ci by český znaky s diakritikou byly až za "z", pokud si to dobře pamatuju...

Dej vědět, jestli jsi tímhle latin2_czech_cs problém vyřešil, pokud jo, utf8 v DB nebudeme řešit, pokud ne, můžu to dohledat :)

**Comment by Skoreto** [comment]
Z <code>latin1_swedish_ci</code> na např. <code>latin2_czech_cs</code> jsem přepnul hned a to problém právě nevyřešilo. Víc jsem se tím nezabýval a postnul to sem, protože se bez toho zatím obejdu. Jen, aby se o té chybě vědělo ;) Nicméně, je to v pořadí :)

Zkusil jsem ještě <code>utf8_czech_ci</code>, ale výsledek z "ěščřžýáíé" -> "?š??žýáíé".

**Comment by TeeJay-net** [comment]
Resolved in https://github.com/Skoreto/FitSpirit/commit/23dce390ee91b872c9405545991081417b950a47
